package com.vinnovateit.latch.common.util

import com.vinnovateit.latch.core.model.PortalSessionRecord
import com.vinnovateit.latch.core.model.SessionSummary
import java.io.OutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Generates an HTML report from a list of session summaries and writes it to an OutputStream.
 * Backward-compatible overload converting legacy SessionSummary items.
 */
fun generateHtmlReport(
    sessions: List<SessionSummary>,
    outputStream: OutputStream,
    appVersion: String
) {
    val portalRecords = sessions.map { session ->
        val durationMs = (session.endTimestamp - session.startTimestamp).coerceAtLeast(0L)
        val mins = durationMs / 60000
        val secs = (durationMs % 60000) / 1000
        val formattedDuration = if (mins > 0) "$mins min $secs sec" else "$secs sec"
        PortalSessionRecord(
            location = "Local Session",
            macAddress = "-",
            loginTime = session.startTimestamp,
            logoutTime = session.endTimestamp,
            durationFormatted = formattedDuration,
            durationMillis = durationMs,
            uploadBytes = session.totalData.txBytes,
            downloadBytes = session.totalData.rxBytes,
            totalBytes = session.totalData.rxBytes + session.totalData.txBytes
        )
    }
    generatePortalHtmlReport(
        sessions = portalRecords,
        outputStream = outputStream,
        appVersion = appVersion,
        userId = ""
    )
}

/**
 * Generates a modern dashboard-styled HTML report from captive portal session records.
 */
fun generatePortalHtmlReport(
    sessions: List<PortalSessionRecord>,
    outputStream: OutputStream,
    appVersion: String,
    userId: String? = ""
) {
    val writer = outputStream.bufferedWriter()
    val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US)
    val generatedAt = dateFormat.format(Date())

    val totalBytes = sessions.sumOf { if (it.totalBytes > 0) it.totalBytes else (it.uploadBytes + it.downloadBytes) }
    val totalUpload = sessions.sumOf { it.uploadBytes }
    val totalDownload = sessions.sumOf { it.downloadBytes }
    val totalDurationMillis = sessions.sumOf { it.durationMillis }
    val sessionCount = sessions.size

    val topLocation = if (sessions.isEmpty()) {
        "N/A"
    } else {
        sessions
            .filter { it.location.isNotBlank() }
            .groupingBy { it.location }
            .eachCount()
            .maxByOrNull { it.value }?.key ?: "N/A"
    }

    val totalDurationFormatted = formatReportDuration(totalDurationMillis)

    val html = buildString {
        appendLine("<!DOCTYPE html>")
        appendLine("<html lang=\"en\">")
        appendLine("<head>")
        appendLine("    <meta charset=\"UTF-8\">")
        appendLine("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
        appendLine("    <title>Latch Session Report</title>")
        appendLine("    <style>")
        appendLine("        :root {")
        appendLine("            --bg: #0f172a;")
        appendLine("            --surface: #1e293b;")
        appendLine("            --surface-hover: #26354a;")
        appendLine("            --border: #334155;")
        appendLine("            --text-primary: #f8fafc;")
        appendLine("            --text-secondary: #94a3b8;")
        appendLine("            --text-muted: #64748b;")
        appendLine("            --accent-blue: #0ea5e9;")
        appendLine("            --accent-green: #10b981;")
        appendLine("            --radius-lg: 14px;")
        appendLine("            --radius-md: 8px;")
        appendLine("            --radius-sm: 6px;")
        appendLine("        }")
        appendLine("        * {")
        appendLine("            box-sizing: border-box;")
        appendLine("            margin: 0;")
        appendLine("            padding: 0;")
        appendLine("        }")
        appendLine("        body {")
        appendLine("            font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif;")
        appendLine("            background-color: var(--bg);")
        appendLine("            color: var(--text-primary);")
        appendLine("            line-height: 1.5;")
        appendLine("            padding: 32px 24px;")
        appendLine("            -webkit-font-smoothing: antialiased;")
        appendLine("        }")
        appendLine("        .container {")
        appendLine("            max-width: 1200px;")
        appendLine("            margin: 0 auto;")
        appendLine("        }")
        appendLine("        /* Header */")
        appendLine("        .header {")
        appendLine("            display: flex;")
        appendLine("            justify-content: space-between;")
        appendLine("            align-items: flex-start;")
        appendLine("            flex-wrap: wrap;")
        appendLine("            gap: 16px;")
        appendLine("            margin-bottom: 28px;")
        appendLine("            padding-bottom: 20px;")
        appendLine("            border-bottom: 1px solid var(--border);")
        appendLine("        }")
        appendLine("        .header-title-group h1 {")
        appendLine("            font-size: 26px;")
        appendLine("            font-weight: 700;")
        appendLine("            color: var(--text-primary);")
        appendLine("            letter-spacing: -0.02em;")
        appendLine("        }")
        appendLine("        .header-title-group .subtitle {")
        appendLine("            color: var(--text-secondary);")
        appendLine("            font-size: 14px;")
        appendLine("            margin-top: 4px;")
        appendLine("        }")
        appendLine("        .meta-tags {")
        appendLine("            display: flex;")
        appendLine("            flex-wrap: wrap;")
        appendLine("            gap: 8px;")
        appendLine("            align-items: center;")
        appendLine("        }")
        appendLine("        .meta-badge {")
        appendLine("            display: inline-flex;")
        appendLine("            align-items: center;")
        appendLine("            padding: 5px 12px;")
        appendLine("            border-radius: var(--radius-sm);")
        appendLine("            font-size: 12px;")
        appendLine("            font-weight: 500;")
        appendLine("            background: var(--surface);")
        appendLine("            border: 1px solid var(--border);")
        appendLine("            color: var(--text-secondary);")
        appendLine("        }")
        appendLine("        .meta-badge strong {")
        appendLine("            color: var(--text-primary);")
        appendLine("            margin-left: 4px;")
        appendLine("        }")
        appendLine("        .meta-badge.user-badge {")
        appendLine("            background: rgba(14, 165, 233, 0.12);")
        appendLine("            border-color: rgba(14, 165, 233, 0.3);")
        appendLine("            color: var(--accent-blue);")
        appendLine("        }")
        appendLine("        .meta-badge.user-badge strong {")
        appendLine("            color: var(--accent-blue);")
        appendLine("        }")
        appendLine("        /* KPI Stat Cards */")
        appendLine("        .stats-grid {")
        appendLine("            display: grid;")
        appendLine("            grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));")
        appendLine("            gap: 20px;")
        appendLine("            margin-bottom: 28px;")
        appendLine("        }")
        appendLine("        .card {")
        appendLine("            background-color: var(--surface);")
        appendLine("            border: 1px solid var(--border);")
        appendLine("            border-radius: var(--radius-lg);")
        appendLine("            padding: 20px;")
        appendLine("            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.2), 0 2px 4px -2px rgba(0, 0, 0, 0.1);")
        appendLine("            display: flex;")
        appendLine("            flex-direction: column;")
        appendLine("            justify-content: space-between;")
        appendLine("        }")
        appendLine("        .card-label {")
        appendLine("            font-size: 12px;")
        appendLine("            font-weight: 600;")
        appendLine("            color: var(--text-secondary);")
        appendLine("            text-transform: uppercase;")
        appendLine("            letter-spacing: 0.05em;")
        appendLine("            margin-bottom: 8px;")
        appendLine("        }")
        appendLine("        .card-value {")
        appendLine("            font-size: 26px;")
        appendLine("            font-weight: 700;")
        appendLine("            color: var(--text-primary);")
        appendLine("            letter-spacing: -0.02em;")
        appendLine("        }")
        appendLine("        .card-caption {")
        appendLine("            font-size: 12px;")
        appendLine("            color: var(--text-muted);")
        appendLine("            margin-top: 8px;")
        appendLine("        }")
        appendLine("        .sub-pills {")
        appendLine("            display: flex;")
        appendLine("            gap: 8px;")
        appendLine("            margin-top: 10px;")
        appendLine("            flex-wrap: wrap;")
        appendLine("        }")
        appendLine("        .sub-pill {")
        appendLine("            display: inline-flex;")
        appendLine("            align-items: center;")
        appendLine("            gap: 4px;")
        appendLine("            font-size: 11px;")
        appendLine("            font-weight: 600;")
        appendLine("            padding: 3px 8px;")
        appendLine("            border-radius: 6px;")
        appendLine("        }")
        appendLine("        .sub-pill.upload {")
        appendLine("            background: rgba(14, 165, 233, 0.15);")
        appendLine("            color: var(--accent-blue);")
        appendLine("        }")
        appendLine("        .sub-pill.download {")
        appendLine("            background: rgba(16, 185, 129, 0.15);")
        appendLine("            color: var(--accent-green);")
        appendLine("        }")
        appendLine("        /* Data Table */")
        appendLine("        .table-container {")
        appendLine("            background-color: var(--surface);")
        appendLine("            border: 1px solid var(--border);")
        appendLine("            border-radius: var(--radius-lg);")
        appendLine("            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.2), 0 2px 4px -2px rgba(0, 0, 0, 0.1);")
        appendLine("            overflow: hidden;")
        appendLine("            margin-bottom: 28px;")
        appendLine("        }")
        appendLine("        .table-header-bar {")
        appendLine("            padding: 16px 20px;")
        appendLine("            border-bottom: 1px solid var(--border);")
        appendLine("            display: flex;")
        appendLine("            justify-content: space-between;")
        appendLine("            align-items: center;")
        appendLine("        }")
        appendLine("        .table-header-bar h2 {")
        appendLine("            font-size: 15px;")
        appendLine("            font-weight: 600;")
        appendLine("            color: var(--text-primary);")
        appendLine("        }")
        appendLine("        .table-wrapper {")
        appendLine("            overflow-x: auto;")
        appendLine("        }")
        appendLine("        table {")
        appendLine("            width: 100%;")
        appendLine("            border-collapse: collapse;")
        appendLine("            font-size: 13px;")
        appendLine("            text-align: left;")
        appendLine("        }")
        appendLine("        thead {")
        appendLine("            background-color: rgba(15, 23, 42, 0.5);")
        appendLine("            border-bottom: 1px solid var(--border);")
        appendLine("        }")
        appendLine("        th {")
        appendLine("            padding: 12px 16px;")
        appendLine("            font-size: 11px;")
        appendLine("            font-weight: 700;")
        appendLine("            text-transform: uppercase;")
        appendLine("            letter-spacing: 0.05em;")
        appendLine("            color: var(--text-secondary);")
        appendLine("            white-space: nowrap;")
        appendLine("        }")
        appendLine("        td {")
        appendLine("            padding: 14px 16px;")
        appendLine("            border-bottom: 1px solid rgba(51, 65, 85, 0.5);")
        appendLine("            color: var(--text-primary);")
        appendLine("            vertical-align: middle;")
        appendLine("            white-space: nowrap;")
        appendLine("        }")
        appendLine("        tbody tr {")
        appendLine("            transition: background-color 0.15s ease;")
        appendLine("        }")
        appendLine("        tbody tr:hover {")
        appendLine("            background-color: var(--surface-hover);")
        appendLine("        }")
        appendLine("        tbody tr:last-child td {")
        appendLine("            border-bottom: none;")
        appendLine("        }")
        appendLine("        .num-col {")
        appendLine("            color: var(--text-muted);")
        appendLine("            width: 32px;")
        appendLine("            font-weight: 500;")
        appendLine("        }")
        appendLine("        .badge {")
        appendLine("            display: inline-flex;")
        appendLine("            align-items: center;")
        appendLine("            padding: 3px 8px;")
        appendLine("            border-radius: var(--radius-sm);")
        appendLine("            font-size: 12px;")
        appendLine("            font-weight: 600;")
        appendLine("        }")
        appendLine("        .badge-location {")
        appendLine("            background-color: rgba(14, 165, 233, 0.12);")
        appendLine("            color: #38bdf8;")
        appendLine("            border: 1px solid rgba(14, 165, 233, 0.25);")
        appendLine("        }")
        appendLine("        .badge-duration {")
        appendLine("            background-color: rgba(148, 163, 184, 0.12);")
        appendLine("            color: #cbd5e1;")
        appendLine("        }")
        appendLine("        .bytes-cell {")
        appendLine("            font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;")
        appendLine("            font-size: 12px;")
        appendLine("        }")
        appendLine("        .empty-row {")
        appendLine("            text-align: center;")
        appendLine("            padding: 36px 16px;")
        appendLine("            color: var(--text-muted);")
        appendLine("        }")
        appendLine("        /* Footer */")
        appendLine("        .footer {")
        appendLine("            text-align: center;")
        appendLine("            font-size: 12px;")
        appendLine("            color: var(--text-muted);")
        appendLine("            padding-top: 12px;")
        appendLine("        }")
        appendLine("        /* Print Styles */")
        appendLine("        @media print {")
        appendLine("            body {")
        appendLine("                background-color: #ffffff !important;")
        appendLine("                color: #0f172a !important;")
        appendLine("                padding: 12px !important;")
        appendLine("            }")
        appendLine("            .header {")
        appendLine("                border-bottom: 2px solid #e2e8f0 !important;")
        appendLine("            }")
        appendLine("            .header-title-group h1 {")
        appendLine("                color: #0f172a !important;")
        appendLine("            }")
        appendLine("            .card {")
        appendLine("                background-color: #f8fafc !important;")
        appendLine("                border: 1px solid #cbd5e1 !important;")
        appendLine("                box-shadow: none !important;")
        appendLine("                page-break-inside: avoid;")
        appendLine("            }")
        appendLine("            .card-label {")
        appendLine("                color: #475569 !important;")
        appendLine("            }")
        appendLine("            .card-value {")
        appendLine("                color: #0f172a !important;")
        appendLine("            }")
        appendLine("            .table-container {")
        appendLine("                background-color: #ffffff !important;")
        appendLine("                border: 1px solid #cbd5e1 !important;")
        appendLine("                box-shadow: none !important;")
        appendLine("            }")
        appendLine("            .table-header-bar {")
        appendLine("                background-color: #f8fafc !important;")
        appendLine("            }")
        appendLine("            .table-header-bar h2 {")
        appendLine("                color: #0f172a !important;")
        appendLine("            }")
        appendLine("            thead {")
        appendLine("                background-color: #f1f5f9 !important;")
        appendLine("                border-bottom: 2px solid #cbd5e1 !important;")
        appendLine("                display: table-header-group;")
        appendLine("            }")
        appendLine("            th {")
        appendLine("                color: #334155 !important;")
        appendLine("            }")
        appendLine("            td {")
        appendLine("                color: #0f172a !important;")
        appendLine("                border-bottom: 1px solid #e2e8f0 !important;")
        appendLine("            }")
        appendLine("            tbody tr {")
        appendLine("                page-break-inside: avoid;")
        appendLine("            }")
        appendLine("            .badge-location {")
        appendLine("                background-color: #f1f5f9 !important;")
        appendLine("                color: #0284c7 !important;")
        appendLine("                border-color: #cbd5e1 !important;")
        appendLine("            }")
        appendLine("            .badge-duration {")
        appendLine("                background-color: #f1f5f9 !important;")
        appendLine("                color: #334155 !important;")
        appendLine("            }")
        appendLine("            .meta-badge {")
        appendLine("                background: #f1f5f9 !important;")
        appendLine("                border-color: #cbd5e1 !important;")
        appendLine("                color: #334155 !important;")
        appendLine("            }")
        appendLine("            .sub-pill.upload {")
        appendLine("                background: #e0f2fe !important;")
        appendLine("                color: #0369a1 !important;")
        appendLine("            }")
        appendLine("            .sub-pill.download {")
        appendLine("                background: #dcfce7 !important;")
        appendLine("                color: #15803d !important;")
        appendLine("            }")
        appendLine("            .footer {")
        appendLine("                color: #64748b !important;")
        appendLine("            }")
        appendLine("        }")
        appendLine("    </style>")
        appendLine("</head>")
        appendLine("<body>")
        appendLine("    <div class=\"container\">")
        appendLine("        <header class=\"header\">")
        appendLine("            <div class=\"header-title-group\">")
        appendLine("                <h1>Latch Session Report</h1>")
        appendLine("                <p class=\"subtitle\">Network diagnostics and captive portal usage overview</p>")
        appendLine("            </div>")
        appendLine("            <div class=\"meta-tags\">")
        if (!userId.isNullOrBlank()) {
            appendLine("                <div class=\"meta-badge user-badge\">User: <strong>${escapeHtml(userId)}</strong></div>")
        }
        appendLine("                <div class=\"meta-badge\">Version: <strong>v${escapeHtml(appVersion)}</strong></div>")
        appendLine("                <div class=\"meta-badge\">Generated: <strong>${escapeHtml(generatedAt)}</strong></div>")
        appendLine("            </div>")
        appendLine("        </header>")
        appendLine("")
        appendLine("        <section class=\"stats-grid\">")
        appendLine("            <div class=\"card\">")
        appendLine("                <div>")
        appendLine("                    <div class=\"card-label\">Total Data Transfer</div>")
        appendLine("                    <div class=\"card-value\">${formatBytes(totalBytes)}</div>")
        appendLine("                </div>")
        appendLine("                <div class=\"sub-pills\">")
        appendLine("                    <span class=\"sub-pill upload\">↑ ${formatBytes(totalUpload)}</span>")
        appendLine("                    <span class=\"sub-pill download\">↓ ${formatBytes(totalDownload)}</span>")
        appendLine("                </div>")
        appendLine("            </div>")
        appendLine("            <div class=\"card\">")
        appendLine("                <div>")
        appendLine("                    <div class=\"card-label\">Total Active Duration</div>")
        appendLine("                    <div class=\"card-value\">$totalDurationFormatted</div>")
        appendLine("                </div>")
        appendLine("                <div class=\"card-caption\">Cumulative connected time</div>")
        appendLine("            </div>")
        appendLine("            <div class=\"card\">")
        appendLine("                <div>")
        appendLine("                    <div class=\"card-label\">Total Sessions Logged</div>")
        appendLine("                    <div class=\"card-value\">$sessionCount ${if (sessionCount == 1) "session" else "sessions"}</div>")
        appendLine("                </div>")
        appendLine("                <div class=\"card-caption\">Historical portal connections</div>")
        appendLine("            </div>")
        appendLine("            <div class=\"card\">")
        appendLine("                <div>")
        appendLine("                    <div class=\"card-label\">Top Location</div>")
        appendLine("                    <div class=\"card-value\">${escapeHtml(topLocation)}</div>")
        appendLine("                </div>")
        appendLine("                <div class=\"card-caption\">Most frequented portal network</div>")
        appendLine("            </div>")
        appendLine("        </section>")
        appendLine("")
        appendLine("        <section class=\"table-container\">")
        appendLine("            <div class=\"table-header-bar\">")
        appendLine("                <h2>Session Details</h2>")
        appendLine("            </div>")
        appendLine("            <div class=\"table-wrapper\">")
        appendLine("                <table>")
        appendLine("                    <thead>")
        appendLine("                        <tr>")
        appendLine("                            <th class=\"num-col\">#</th>")
        appendLine("                            <th>Location</th>")
        appendLine("                            <th>Login Time</th>")
        appendLine("                            <th>Logout Time</th>")
        appendLine("                            <th>Duration</th>")
        appendLine("                            <th>Upload</th>")
        appendLine("                            <th>Download</th>")
        appendLine("                            <th>Total Data</th>")
        appendLine("                        </tr>")
        appendLine("                    </thead>")
        appendLine("                    <tbody>")
        if (sessions.isEmpty()) {
            appendLine("                        <tr>")
            appendLine("                            <td colspan=\"8\" class=\"empty-row\">No session data available.</td>")
            appendLine("                        </tr>")
        } else {
            sessions.forEachIndexed { index, session ->
                val loginTimeStr = if (session.loginTime > 0) dateFormat.format(Date(session.loginTime)) else "-"
                val logoutTimeStr = if (session.logoutTime > 0) dateFormat.format(Date(session.logoutTime)) else "-"
                val durationStr = session.durationFormatted.ifBlank { formatReportDuration(session.durationMillis) }
                val rowTotal = if (session.totalBytes > 0) session.totalBytes else (session.uploadBytes + session.downloadBytes)

                appendLine("                        <tr>")
                appendLine("                            <td class=\"num-col\">${index + 1}</td>")
                appendLine("                            <td><span class=\"badge badge-location\">${escapeHtml(session.location.ifBlank { "Unknown" })}</span></td>")
                appendLine("                            <td>${escapeHtml(loginTimeStr)}</td>")
                appendLine("                            <td>${escapeHtml(logoutTimeStr)}</td>")
                appendLine("                            <td><span class=\"badge badge-duration\">${escapeHtml(durationStr)}</span></td>")
                appendLine("                            <td class=\"bytes-cell\">${formatBytes(session.uploadBytes)}</td>")
                appendLine("                            <td class=\"bytes-cell\">${formatBytes(session.downloadBytes)}</td>")
                appendLine("                            <td class=\"bytes-cell\">${formatBytes(rowTotal)}</td>")
                appendLine("                        </tr>")
            }
        }
        appendLine("                    </tbody>")
        appendLine("                </table>")
        appendLine("            </div>")
        appendLine("        </section>")
        appendLine("")
        appendLine("        <footer class=\"footer\">")
        appendLine("            Generated automatically by Latch v${escapeHtml(appVersion)}")
        appendLine("        </footer>")
        appendLine("    </div>")
        appendLine("</body>")
        appendLine("</html>")
    }

    writer.write(html)
    writer.flush()
    writer.close()
}

private fun formatBytes(bytes: Long): String {
    return when {
        bytes >= 1024L * 1024L * 1024L -> "%.2f GB".format(Locale.US, bytes / (1024.0 * 1024.0 * 1024.0))
        bytes >= 1024L * 1024L -> "%.2f MB".format(Locale.US, bytes / (1024.0 * 1024.0))
        bytes >= 1024L -> "%.2f KB".format(Locale.US, bytes / 1024.0)
        else -> "$bytes B"
    }
}

private fun formatReportDuration(millis: Long): String {
    if (millis <= 0) return "0 sec"
    val totalSeconds = millis / 1000
    val hours = totalSeconds / 3600
    val minutes = (totalSeconds % 3600) / 60
    val seconds = totalSeconds % 60
    return buildString {
        if (hours > 0) append("$hours hr ")
        if (minutes > 0 || hours > 0) append("$minutes min ")
        if (seconds > 0 || (hours == 0L && minutes == 0L)) append("$seconds sec")
    }.trim()
}

private fun escapeHtml(text: String): String {
    return text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")
        .replace("'", "&#39;")
}